# Cloudflare Pages 配置 - 幻境之旅生成器
name = "huanjing-zhilv-generator"
compatibility_date = "2024-06-08"

# 使用 Cloudflare Pages 而不是 Workers Site
# 这更适合React SPA应用的部署

[vars]
ENVIRONMENT = "production"
NODE_ENV = "production"

# 部署说明：
# 1. 首先构建项目：npm run build
# 2. 使用 Cloudflare Pages 部署：npx wrangler pages deploy dist
# 3. 设置环境变量：npx wrangler pages secret put GEMINI_API_KEY 